// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCqmOmE6PBZWkmVQlT4NnLwiF1C7PxPKA',
    appId: '1:1061318495223:web:f043a60c107a09ec87bcf2',
    messagingSenderId: '1061318495223',
    projectId: 'login-2eb09',
    authDomain: 'login-2eb09.firebaseapp.com',
    storageBucket: 'login-2eb09.appspot.com',
    measurementId: 'G-FXFNCXEFLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-7Plaz9klRqUwyO8EFEuhODS5Xg28oY',
    appId: '1:1061318495223:android:a14f807c6226879c87bcf2',
    messagingSenderId: '1061318495223',
    projectId: 'login-2eb09',
    storageBucket: 'login-2eb09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC62vW7xQu8x1P8oZeDvr444MKtmOjMyAs',
    appId: '1:1061318495223:ios:7e17c558b9ff6bac87bcf2',
    messagingSenderId: '1061318495223',
    projectId: 'login-2eb09',
    storageBucket: 'login-2eb09.appspot.com',
    iosBundleId: 'com.example.jobPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC62vW7xQu8x1P8oZeDvr444MKtmOjMyAs',
    appId: '1:1061318495223:ios:7e17c558b9ff6bac87bcf2',
    messagingSenderId: '1061318495223',
    projectId: 'login-2eb09',
    storageBucket: 'login-2eb09.appspot.com',
    iosBundleId: 'com.example.jobPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCqmOmE6PBZWkmVQlT4NnLwiF1C7PxPKA',
    appId: '1:1061318495223:web:bbfd7d2ddbf68a8c87bcf2',
    messagingSenderId: '1061318495223',
    projectId: 'login-2eb09',
    authDomain: 'login-2eb09.firebaseapp.com',
    storageBucket: 'login-2eb09.appspot.com',
    measurementId: 'G-39KF9P1KCZ',
  );
}
